a=input('digite algo?')
print('o tipo primitivo desse valor e', type(a))
print('e so tem espacos?', a.isspace())
print('e so tem numeros?', a.isnumeric())
print('e alfabetico?', a.isalpha())
print('e alfanumeirco?', a.isalnum())